INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (1, 'АвтоЗвук', 1, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (2, 'Автобудинок', 2, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (3, 'Мустанг', 3, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (4, 'Елітавто', 4, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (5, 'Авто світ', 1, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (6, 'Автошара', 2, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (7, 'Сінта-Трейд', 3, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (8, 'АвтоАптека', 4, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (9, 'Арсенал', 1, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (10, 'ШипШина', 2, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (11, 'Редмоторс', 3, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (12, 'Віанор', 4, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (13, 'АвтоСпа', 1, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (14, 'Новатон', 2, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (15, 'Кренель', 3, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (16, 'Авто Олімп', 4, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (17, 'Індастріал Тайрс', 1, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (18, 'АвтоГараж', 2, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (19, 'Світлофор', 3, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (20, 'ЛеоПартс', 4, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (21, 'АвтоОіл', 1, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (22, 'Олкар', 2, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (23, 'Євродеталь', 3, 1);
INSERT INTO AutoPartsStore.suppliers (supplier_id, supplier_name, supplier_category_id, supplier_status_id) VALUES (24, 'Демекс', 4, 1);
